import type { Metadata } from "next";
import HeroUiProvider from "@/components/ui/HeroUiProvider";
import "./globals.css";
import { Montserrat } from 'next/font/google'
 
const montserrat = Montserrat({
  subsets: ['latin'],
})



export const metadata: Metadata = {
  title: "Eatopia",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en" className={montserrat.className}>
      <body className="bg-white">
        <HeroUiProvider>
          <main>{children}</main>
        </HeroUiProvider>
      </body>
    </html>
  );
}
