import type { Metadata } from "next";
import HeroUiProvider from "@/components/ui/HeroUiProvider";
import "./globals.css";

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body className="">
        <HeroUiProvider>
          <main className="h-full ">{children}</main>
        </HeroUiProvider>
      </body>
    </html>
  );
}
